name: Build and Create Release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      message:
        description: 'Release note'
        required: true

jobs:
  build:
    name: Run Build
    uses: OxideMod/Actions/.github/workflows/game-build.yml@main
    with:
      game: "SevenDaysToDie"
    secrets: inherit

  release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: artifacts

      - name: Deploy to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/Oxide.*.zip
          tag_name: 2.0.${{ vars.VERSION }}
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            See https://umod.org/games/7-days-to-die for changes
